#Absenderadresse
email.sender=no-reply-sport-saison-notifier@hr.de
# application.properties
email.recipients=hamid.azimi@hr.de,jasan.chahrrour@hr.de,laura.mai@hr.de
email.subject=Spielinformationen

email.thresholdDays=100
email.host=http://localhost
server.port=8084

fileStorageRestServiceUrl=http://localhost:8085
fileStorageRestServicePath=/api/v1/dmx4/filestorage/
fileStorageThema=sport/saison/notifier/table
fileStorageName=table.xls

