# application.properties
spring.mail.host=relay.mail.sec-provider.de
spring.mail.username=outbound-hr
spring.mail.password=BHugk9h1.
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false
#Absenderadresse
email.sender=${EMAIL_SENDER}
email.recipients=${EMAIL_RECIPIENTS}
email.setfrom=${}
email.subject=${EMAIL_SUBJECT}
email.thresholdDays=${EMAIL_THRESHOLD_DAYS}
email.host=${EMAIL_HOST}

fileStorageRestServiceUrl=${FILESTORAGE_SERVICE_HOST_URL}
fileStorageRestServicePath=${FILESTORAGE_SERVICE_ROOT_PATH}
fileStorageThema=${FILESTORAGE_THEMA}
fileStorageName=${FILESTORAGE_NAME}

